[project]
name = "health-monitoring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "environs>=14.2.0",
    "playwright>=1.53.0",
    "requests>=2.32.4",
]
